Example unacceptable behavior examples
MetaMask/.github pull request #43
Opened 2023-07-10 15:38 UTC by brad-decker

Adds a bullet to the list of unacceptable behavior examples to indicate that unwanted communication outside of GitHub to draw attention to GitHub is a form of unacceptable behavior.

2023-07-10 15:49 UTC, DDDDDanica approved these changes

2023-07-10 16:38 UTC, pedronfigueiredo approved these changes

2023-07-10 21:08 UTC, digiwand approved these changes

2023-07-11 11:41 UTC, Gudahtt approved these changes
LGTM!

2023-07-12 17:36 UTC, merged

2025-08-06 12:57 UTC, hardikgosai1 requested changes
Change